////
= Critères de séléctions
v3.0
:icons: font
:check: icon:check[role="green"]
:uncheck: icon:times[role="red"]

****
[red]_Regroupement des différents critères qui permettront de choisir la solution la plus adaptée._
****

---
////
{check} : Possible (intégré directement,via plugins,...) +
{uncheck} : Impossible +
//{almost} : Possible sous conditions (via plugins,...) +
//{question} : Pas d'informations

[horizontal]
.Impératif
Licences::
    Avons nous accès à la version complète du produit ou une version réduite d'un produit commercial ? Accès aux dernières sources disponibles ? +
    _Libre (type de Licence)/Limité/Commerciale - Sources accessible/Non accessible_

Développement (Dernière update et date)::
    Est-ce que le développement est actif ? +
    _Actif/Inactif - Date et version de la dernière update_

Communauté::
    La communauté est elle active ? La documentation est présente et complète ? +
    _Active/Inactive - Forum/Mailing list/Temps de réponse_

Web API::
    Pouvons nous avoir accès à une interface web ? (Intégrée, détachée,...) Si oui est elle personnalisable ? (Tableaux de bords, choix des vues,... ) +
    {check}/{uncheck} _- Personnalisable/Non personnalisable_

OS supportés::
    _Windows/Linux_

Triggers/Alerts::
    Est-il possible de remonter des alertes quand il le faut et déclencher des évènements pour réagir en fonction ? Par quels moyens ? +
    {check}/{uncheck} _- sms/mail/jabber/slack/IRC/Customs alertscripts,..._

Agentless::
    Est-il possible de superviser une plateforme sans installer l'agent ? Si oui par quels moyens ? (Services réseaux, SSH, NRPE,...) +
    {check}/{uncheck} _- SSH/NRPE/TCP/ICMP/..._

SNMP ( Simple Network Management Protocol )::
    Supervision de la plupart des équipements : switch, firewall, routeurs, UPS,... +
    {check}/{uncheck}

---

[horizontal]
.Souhaitable
Supervision distribuée (scalability)::
    Autoriser l'environement à s'élargir et à superviser des infrastructures plus larges. Superviser plusieurs sites avec une seule installation. +
    {check}/{uncheck}

Configuration::
    Quelles sont les méthodes de configuration ? Depuis la console via des fichier de configuration ? Depuis une API ? Configuration simple ? Rapide ? +
    _Fichiers(type de fichiers) - CLI/API_

Plugins::
    A-t-on la possibilité de rajouter des plugins existants ? D'utiliser les plugins Nagios ? De creer les siens ? +
    {check}/{uncheck} _- nagios/personnels/autres_

Compatibilité nagios::
    Peut-on rapidement remettre en place le système déjà présent ou faut-il repartir de zéro ? +
    {check}/{uncheck}

Gestion des utilisateurs::
    Est-il possible de créer et de gérer différents niveaux d'utilisateurs. Donner certains droits à certains utilisateurs ? +
    {check}/{uncheck}

---

[horizontal]
.Facultatif
Graphiques et visualisation::
    Est-il possible d'avoir un rendu des données récoltés pour avoir un visuel de ce que l'on supervise ? Est-ce directement intégré à la solution ? Faut-il installer des modules supplémentaires pour y avoir accès ? +
    {check}/{uncheck} _- Intégrés/Importés_

Installation::
    L'installation est simple ? Rapide ? Plusieurs modules à installer ? +
    _Simple/Laborieuse - Rapide/Longue - Tout en un/Modulable_

Application Mobile::
    Peut-on recevoir les alertes sur son téléphone ? +
    {check}/{uncheck}

Support::
    Les développeurs fournissent-ils un support ? Si oui, est-il gratuit ou payant ? +
    _Actif/Inactif - Payant/Gratuit_

Prédiction des tendances (Trend prediction)::
    La trend prediction regarde comment l'infrastructure s'est comportée au fil du temps et essais de prédire comment elle risque de se comporter dans le futur, dans un but de prédiction et de prévention pour éventuellement résoudre les problèmes avant qu'ils ne soient détéctés et qu'ils ne deviennent réellement des problèmes. +
    {check}/{uncheck}

Découverte automatique (Auto Discovery)::
    L'auto-discovery, ajoute automatiquement dans le système les nouveaux équipements qui ont été ajouté au réseau. +
    {check}/{uncheck}

Syslog::
    La gestion des logs est-elle intégrée ? +
    {check}/{uncheck}

Isolement/Détection des problèmes::
    Cette fonctionnalité permet d'identifier et d'isoler la réelle source du problème pour limiter les alertes et pour permettre une résolution simplifiée. +
    {check}/{uncheck}

Desktop API::
    Peut-on utiliser une interface graphique de bureau, pour éviter de passer par un explorateur internet ? +
    {check}/{uncheck}

Langages utilisés::
    Quels langages sont utilisés ? Il est parfois plus facile d'utiliser tel ou tel language dans certaines conditions.+
    _Python/C/java/..._

Methode de stockage des données::
    Quelles sont les bases de données utilisées ? +
    _MySQL/PostgreSQL/RRDTool/Oracle/..._

Map du réseau::
    Peut-on accéder à une map du réseau, pour avoir un aperçu du réseau et de la relations entre ses différents équipements ? +
    {check}/{uncheck}
